-- =====================================================
-- 개발 요청 게시판: 요청 수정/삭제 및 댓글 기능 추가
-- add_development_requests.sql을 이미 실행한 경우 이 파일 하나만 실행하세요.
-- =====================================================

create or replace function public.guard_development_request_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_beadyo_editor() and (
    new.id is distinct from old.id
    or new.requester_id is distinct from old.requester_id
    or new.requester_name is distinct from old.requester_name
    or new.requester_avatar is distinct from old.requester_avatar
    or new.status is distinct from old.status
    or new.created_at is distinct from old.created_at
  ) then
    raise exception '요청자는 요청 내용만 수정할 수 있습니다.' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists development_requests_guard_update on public.development_requests;
create trigger development_requests_guard_update
before update on public.development_requests
for each row execute function public.guard_development_request_update();

drop policy if exists "본인 요청 수정" on public.development_requests;
create policy "본인 요청 수정" on public.development_requests
  for update to authenticated
  using (requester_id = auth.uid())
  with check (requester_id = auth.uid());

drop policy if exists "본인 요청 삭제" on public.development_requests;
create policy "본인 요청 삭제" on public.development_requests
  for delete to authenticated
  using (requester_id = auth.uid());

drop policy if exists "편집자 요청 삭제" on public.development_requests;
create policy "편집자 요청 삭제" on public.development_requests
  for delete to authenticated
  using (public.is_beadyo_editor());

grant select, insert, update, delete on table public.development_requests to authenticated;

create table if not exists public.development_request_comments (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.development_requests(id) on delete cascade,
  author_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  author_name text not null check (char_length(author_name) between 1 and 80),
  author_avatar text,
  content text not null check (char_length(btrim(content)) between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_development_request_comments_request_created
  on public.development_request_comments(request_id, created_at asc);

create or replace function public.touch_development_request_comment_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists development_request_comments_touch_updated_at on public.development_request_comments;
create trigger development_request_comments_touch_updated_at
before update on public.development_request_comments
for each row execute function public.touch_development_request_comment_updated_at();

create or replace function public.guard_development_request_comment_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_beadyo_editor() and (
    new.id is distinct from old.id
    or new.request_id is distinct from old.request_id
    or new.author_id is distinct from old.author_id
    or new.author_name is distinct from old.author_name
    or new.author_avatar is distinct from old.author_avatar
    or new.created_at is distinct from old.created_at
  ) then
    raise exception '댓글 작성자는 댓글 내용만 수정할 수 있습니다.' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists development_request_comments_guard_update on public.development_request_comments;
create trigger development_request_comments_guard_update
before update on public.development_request_comments
for each row execute function public.guard_development_request_comment_update();

alter table public.development_request_comments enable row level security;

drop policy if exists "로그인 사용자 댓글 조회" on public.development_request_comments;
create policy "로그인 사용자 댓글 조회" on public.development_request_comments
  for select to authenticated
  using (true);

drop policy if exists "본인 댓글 등록" on public.development_request_comments;
create policy "본인 댓글 등록" on public.development_request_comments
  for insert to authenticated
  with check (author_id = auth.uid());

drop policy if exists "본인 댓글 수정" on public.development_request_comments;
create policy "본인 댓글 수정" on public.development_request_comments
  for update to authenticated
  using (author_id = auth.uid())
  with check (author_id = auth.uid());

drop policy if exists "편집자 댓글 수정" on public.development_request_comments;
create policy "편집자 댓글 수정" on public.development_request_comments
  for update to authenticated
  using (public.is_beadyo_editor())
  with check (public.is_beadyo_editor());

drop policy if exists "본인 댓글 삭제" on public.development_request_comments;
create policy "본인 댓글 삭제" on public.development_request_comments
  for delete to authenticated
  using (author_id = auth.uid());

drop policy if exists "편집자 댓글 삭제" on public.development_request_comments;
create policy "편집자 댓글 삭제" on public.development_request_comments
  for delete to authenticated
  using (public.is_beadyo_editor());

revoke all on table public.development_request_comments from anon;
grant select, insert, update, delete on table public.development_request_comments to authenticated;
grant usage, select on sequence public.development_request_comments_id_seq to authenticated;
