-- =====================================================
-- 개발 요청 게시판
-- Supabase Dashboard → SQL Editor에서 한 번 실행하세요.
-- =====================================================

create or replace function public.is_beadyo_editor()
returns boolean
language sql
security definer
set search_path = public
as $$
  select
    lower(coalesce(auth.jwt() ->> 'email', '')) = 'riosniper12@gmail.com'
    or exists (
      select 1
      from public.editors e
      where lower(e.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    );
$$;

create table if not exists public.development_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  requester_name text not null check (char_length(requester_name) between 1 and 80),
  requester_avatar text,
  content text not null check (char_length(btrim(content)) between 1 and 2000),
  status text not null default 'received' check (status in ('received', 'in_progress', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_development_requests_created_at
  on public.development_requests(created_at desc);

create index if not exists idx_development_requests_status
  on public.development_requests(status);

create or replace function public.touch_development_request_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists development_requests_touch_updated_at on public.development_requests;
create trigger development_requests_touch_updated_at
before update on public.development_requests
for each row execute function public.touch_development_request_updated_at();

create or replace function public.guard_development_request_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_beadyo_editor() and (
    new.id is distinct from old.id
    or new.requester_id is distinct from old.requester_id
    or new.requester_name is distinct from old.requester_name
    or new.requester_avatar is distinct from old.requester_avatar
    or new.status is distinct from old.status
    or new.created_at is distinct from old.created_at
  ) then
    raise exception '요청자는 요청 내용만 수정할 수 있습니다.' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists development_requests_guard_update on public.development_requests;
create trigger development_requests_guard_update
before update on public.development_requests
for each row execute function public.guard_development_request_update();

alter table public.development_requests enable row level security;

drop policy if exists "로그인 사용자 요청 조회" on public.development_requests;
create policy "로그인 사용자 요청 조회" on public.development_requests
  for select to authenticated
  using (true);

drop policy if exists "본인 요청 등록" on public.development_requests;
create policy "본인 요청 등록" on public.development_requests
  for insert to authenticated
  with check (
    requester_id = auth.uid()
    and status = 'received'
  );

drop policy if exists "편집자 상태 변경" on public.development_requests;
create policy "편집자 상태 변경" on public.development_requests
  for update to authenticated
  using (public.is_beadyo_editor())
  with check (public.is_beadyo_editor());

drop policy if exists "본인 요청 수정" on public.development_requests;
create policy "본인 요청 수정" on public.development_requests
  for update to authenticated
  using (requester_id = auth.uid())
  with check (requester_id = auth.uid());

drop policy if exists "본인 요청 삭제" on public.development_requests;
create policy "본인 요청 삭제" on public.development_requests
  for delete to authenticated
  using (requester_id = auth.uid());

drop policy if exists "편집자 요청 삭제" on public.development_requests;
create policy "편집자 요청 삭제" on public.development_requests
  for delete to authenticated
  using (public.is_beadyo_editor());

revoke all on table public.development_requests from anon;
grant select, insert, update, delete on table public.development_requests to authenticated;
grant usage, select on sequence public.development_requests_id_seq to authenticated;
